version: "3"

services:
  app:
    container_name: app-dev
    build:
      context: .
      dockerfile: ./react.dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - '3000:3000'
    entrypoint: ['yarn']
