export const API_STATS_COUNTRY = process.env.REACT_APP_API_DATA_COUNTRY
export const API_STATS_COVID_COUNTRY = process.env.REACT_APP_API_STATS_COVID_COUNTRY
export const APP_API_DATA_WORLD = process.env.REACT_APP_API_DATA_WORLD